# Assignment no. 3- Write a python program to display IMDB’s Top rated 100 Indian movies’ data (i.e. Name, IMDB rating, Year of release) and save it in form of a CSV file.

In [1]:
# importing the required libraries
from bs4 import BeautifulSoup
import requests

In [2]:
page=requests.get("https://www.imdb.com/india/top-rated-indian-movies/")

In [3]:
soup=BeautifulSoup(page.content,'html.parser')

In [4]:
Movie_Name=[]
IMDB_Rating=[]
Year_of_Release=[]

In [5]:
titles2=soup.find_all('td',class_="titleColumn")
for i in titles2:
        full_name=i.find('a').get_text()
        Movie_Name.append(full_name)

In [6]:
Movie_Name

['Pather Panchali',
 'Gol Maal',
 'Ratsasan',
 'Nayakan',
 'Anbe Sivam',
 'Apur Sansar',
 'Kireedam',
 'Natsamrat',
 'Pariyerum Perumal',
 'Black Friday',
 'Thevar Magan',
 'Manichitrathazhu',
 '96',
 'Kumbalangi Nights',
 '3 Idiots',
 'Taare Zameen Par',
 'Visaaranai',
 'Dangal',
 'Anand',
 'Thalapathi',
 'Aparajito',
 'Vikram Vedha',
 'Jaane Bhi Do Yaaro',
 'Pyaasa',
 'Asuran',
 'Guide',
 'Kannathil Muthamittal',
 'Chupke Chupke',
 'Jersey',
 'Kaithi',
 'Thani Oruvan',
 'Vada Chennai',
 'Soorarai Pottru',
 'Khosla Ka Ghosla!',
 'Drishyam',
 'Aruvi',
 'Super Deluxe',
 'Peranbu',
 'Andhadhun',
 'Tumbbad',
 'Agent Sai Srinivasa Athreya',
 'Mahanati',
 'Kaakkaa Muttai',
 'Premam',
 'Dhuruvangal Pathinaaru',
 'Satya',
 'Shahid',
 'Bangalore Days',
 'Soodhu Kavvum',
 'Mudhalvan',
 'Anniyan',
 'Gangs of Wasseypur',
 'Papanasam',
 'Jigarthanda',
 'Talvar',
 'Paan Singh Tomar',
 'Bhaag Milkha Bhaag',
 'Nil Battey Sannata',
 'Swades: We, the People',
 'Hera Pheri',
 'Sholay',
 'Drishyam',
 'Pithamagan',
 'Black',
 'Chak De! India',
 'Jo Jeeta Wohi Sikandar',
 'Charulata',
 'Sairat',
 'Mughal-E-Azam',
 'Rang De Basanti',
 'Queen',
 'Ustad Hotel',
 'Udaan',
 'Article 15',
 'Zindagi Na Milegi Dobara',
 'A Wednesday',
 'Dil Chahta Hai',
 'Munna Bhai M.B.B.S.',
 'Andaz Apna Apna',
 'Sarfarosh',
 'Masaan',
 'OMG: Oh My God!',
 'Roja',
 'Lagaan: Once Upon a Time in India',
 'Maheshinte Prathikaaram',
 'Kahaani',
 'Alai Payuthey',
 'Theeran adhigaaram ondru',
 'PK',
 'Baasha',
 'Uri: The Surgical Strike',
 'Iqbal',
 'Pink',
 'Barfi!',
 'The Legend of Bhagat Singh',
 'Bommarillu',
 'Maqbool',
 'Bombay',
 'Lucia',
 'Omkara',
 'Section 375',
 'Lage Raho Munna Bhai',
 'Deewaar',
 'Indian',
 'Chhichhore',
 'Baahubali 2: The Conclusion',
 'Dilwale Dulhania Le Jayenge',
 'Padosan',
 'Gulaal',
 'Haider',
 'Gully Boy',
 'Pelli Choopulu',
 'Mother India',
 'Athadu',
 'Ugly',
 'Padayappa',
 'Special Chabbis',
 'Dev.D',
 'Rangasthalam',
 'Jalsaghar',
 'Badhaai ho',
 'Ship of Theseus',
 'Bajrangi Bhaijaan',
 'Vaastav: The Reality',
 'Company',
 'Ulidavaru Kandanthe',
 'Arjun Reddy',
 'Ankhon Dekhi',
 'Mukkabaaz',
 'Vaaranam Aayiram',
 'Vedam',
 'Manjhi: The Mountain Man',
 'K.G.F: Chapter 1',
 'Dil Bechara',
 'Pizza',
 'My Name Is Khan',
 'Jab We Met',
 'Kal Ho Naa Ho',
 'Mumbai Police',
 'Memories',
 'Unnaipol Oruvan',
 'Padman',
 'Border',
 'Bãhubali: The Beginning',
 'Lakshya',
 'Dor',
 'Super 30',
 'Airlift',
 'Vettaiyaadu Vilaiyaadu',
 'Baby',
 'Hey Ram',
 'English Vinglish',
 'Charlie',
 'Gangaajal',
 'Okkadu',
 'The Lunchbox',
 'Ab Tak Chhappan',
 'Hindi Medium',
 'Johnny Gaddaar',
 'Manam',
 'Secret Superstar',
 'Badla',
 'Sonchiriya',
 'Raazi',
 'Nayak: The Real Hero',
 'Vicky Donor',
 'Mr. India',
 'Udta Punjab',
 'Don',
 'Pokiri',
 'Stanley Ka Dabba',
 'Rock On!!',
 'Dasvidaniya',
 'Veer-Zaara',
 'RangiTaranga',
 'Samsara',
 'Aligarh',
 'Guru',
 'Arya',
 'Oye Lucky! Lucky Oye!',
 'Velaiilla Pattadhari',
 'Goodachari',
 'M.S. Dhoni: The Untold Story',
 'Mumbai Meri Jaan',
 'Kai po che!',
 'Kapoor & Sons',
 'Rockstar',
 'Aamir',
 'Eega',
 'Kabhi Haan Kabhi Naa',
 'Darr',
 'Newton',
 '24',
 'Earth',
 'Agneepath',
 'Madras Cafe',
 'Ugramm',
 'Pyaar Ka Punchnama',
 'Sarkar',
 'Neerja',
 'Bheja Fry',
 'Highway',
 'The Tashkent Files',
 'Manorama: Six Feet Under',
 'Thuppakki',
 'Detective Byomkesh Bakshy!',
 'Magadheera',
 'Baazigar',
 'Tanu Weds Manu Returns',
 'Nerkonda Paarvai',
 'Saala Khadoos',
 'Wake Up Sid',
 'Piku',
 'Ludo',
 'Kuch Kuch Hota Hai',
 'Sanju',
 'Kaththi',
 '1 - Nenokkadine',
 'Delhi Belly',
 'Dhruva',
 'Stree',
 'Devdas',
 'Jodhaa Akbar',
 'Parmanu: The Story of Pokhran',
 'Lootcase',
 'Raanjhanaa',
 'Trapped',
 'Dil Se..',
 'Ek Hasina Thi',
 'Rocket Singh: Salesman of the Year',
 'Bhavesh Joshi Superhero',
 'Hungama',
 'Do Dooni Chaar',
 'Madaari',
 'Jolly LLB',
 'Rehnaa Hai Terre Dil Mein',
 'Jallikattu',
 'Geetha Govindam',
 'The Ghazi Attack',
 'Bareilly Ki Barfi',
 'Karwaan',
 'Phas Gaye Re Obama',
 'Ghajini',
 'Ghilli',
 'Qayamat Se Qayamat Tak',
 'Dum Laga Ke Haisha',
 'The Sky Is Pink',
 'Hichki',
 'Sivaji',
 'October']

In [7]:
len(Movie_Name)

250

In [8]:
ratings=soup.find_all('td',class_="ratingColumn imdbRating")
ratings

[<td class="ratingColumn imdbRating">
 <strong title="8.5 based on 23,331 user ratings">8.5</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.5 based on 17,916 user ratings">8.5</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.5 based on 23,545 user ratings">8.5</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.5 based on 16,105 user ratings">8.5</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.5 based on 16,577 user ratings">8.5</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.4 based on 11,968 user ratings">8.4</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.4 based on 5,770 user ratings">8.4</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.4 based on 5,152 user ratings">8.4</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.4 based on 8,475 user ratings">8.4</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.4 based on 18,783 user ratings">8.4</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.4 based on 5,332 user ratings">8.4</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.4 based on 8,430 user ratings">8.4</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.4 based on 18,559 user ratings">8.4</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.4 based on 8,708 user ratings">8.4</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.4 based on 342,285 user ratings">8.4</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.3 based on 167,635 user ratings">8.3</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.3 based on 7,451 user ratings">8.3</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.3 based on 154,978 user ratings">8.3</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.3 based on 29,923 user ratings">8.3</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.3 based on 9,980 user ratings">8.3</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.3 based on 11,569 user ratings">8.3</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.3 based on 27,656 user ratings">8.3</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.3 based on 13,147 user ratings">8.3</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.3 based on 5,489 user ratings">8.3</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.3 based on 10,432 user ratings">8.3</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.3 based on 7,385 user ratings">8.3</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.2 based on 7,409 user ratings">8.2</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.2 based on 11,589 user ratings">8.2</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.2 based on 7,928 user ratings">8.2</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.2 based on 11,101 user ratings">8.2</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.2 based on 16,496 user ratings">8.2</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.2 based on 10,719 user ratings">8.2</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.2 based on 51,906 user ratings">8.2</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.2 based on 22,203 user ratings">8.2</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.2 based on 30,562 user ratings">8.2</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.2 based on 10,816 user ratings">8.2</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.2 based on 9,480 user ratings">8.2</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.2 based on 12,405 user ratings">8.2</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.2 based on 70,849 user ratings">8.2</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.2 based on 27,182 user ratings">8.2</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.2 based on 6,513 user ratings">8.2</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.2 based on 9,641 user ratings">8.2</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.2 based on 5,549 user ratings">8.2</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.2 based on 16,926 user ratings">8.2</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.2 based on 12,259 user ratings">8.2</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.2 based on 13,378 user ratings">8.2</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.2 based on 15,145 user ratings">8.2</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.1 based on 16,282 user ratings">8.1</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.1 based on 8,860 user ratings">8.1</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.1 based on 6,373 user ratings">8.1</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.1 based on 14,339 user ratings">8.1</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.1 based on 81,756 user ratings">8.1</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.1 based on 5,754 user ratings">8.1</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.1 based on 10,123 user ratings">8.1</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.1 based on 30,959 user ratings">8.1</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.1 based on 33,102 user ratings">8.1</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.1 based on 60,881 user ratings">8.1</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.1 based on 5,613 user ratings">8.1</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.1 based on 82,713 user ratings">8.1</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.1 based on 56,749 user ratings">8.1</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.1 based on 51,129 user ratings">8.1</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.1 based on 69,639 user ratings">8.1</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.1 based on 5,089 user ratings">8.1</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.1 based on 33,268 user ratings">8.1</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.1 based on 73,744 user ratings">8.1</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.1 based on 21,583 user ratings">8.1</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.1 based on 5,074 user ratings">8.1</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.1 based on 11,326 user ratings">8.1</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.1 based on 7,300 user ratings">8.1</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.1 based on 111,461 user ratings">8.1</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.1 based on 60,481 user ratings">8.1</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.1 based on 11,614 user ratings">8.1</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.1 based on 42,208 user ratings">8.1</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.1 based on 23,144 user ratings">8.1</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.1 based on 67,512 user ratings">8.1</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.1 based on 73,680 user ratings">8.1</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.1 based on 66,536 user ratings">8.1</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.1 based on 73,679 user ratings">8.1</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.1 based on 49,138 user ratings">8.1</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.1 based on 23,889 user ratings">8.1</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.1 based on 23,549 user ratings">8.1</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.1 based on 51,449 user ratings">8.1</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.1 based on 11,628 user ratings">8.1</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.1 based on 104,619 user ratings">8.1</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.1 based on 6,671 user ratings">8.1</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.1 based on 57,577 user ratings">8.1</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.1 based on 5,203 user ratings">8.1</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.1 based on 9,978 user ratings">8.1</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.1 based on 161,928 user ratings">8.1</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.1 based on 8,737 user ratings">8.1</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.1 based on 43,053 user ratings">8.1</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.1 based on 15,846 user ratings">8.1</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.1 based on 38,928 user ratings">8.1</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.0 based on 75,440 user ratings">8.0</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.0 based on 14,730 user ratings">8.0</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.0 based on 8,530 user ratings">8.0</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.0 based on 9,491 user ratings">8.0</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.0 based on 11,271 user ratings">8.0</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.0 based on 11,465 user ratings">8.0</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.0 based on 19,131 user ratings">8.0</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.0 based on 11,595 user ratings">8.0</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.0 based on 42,966 user ratings">8.0</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.0 based on 10,073 user ratings">8.0</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.0 based on 10,603 user ratings">8.0</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.0 based on 33,269 user ratings">8.0</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.0 based on 74,747 user ratings">8.0</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.0 based on 63,248 user ratings">8.0</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.0 based on 6,201 user ratings">8.0</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.0 based on 13,890 user ratings">8.0</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.0 based on 50,280 user ratings">8.0</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.0 based on 31,537 user ratings">8.0</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.0 based on 5,794 user ratings">8.0</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.0 based on 8,524 user ratings">8.0</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.0 based on 11,974 user ratings">8.0</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.0 based on 20,079 user ratings">8.0</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.0 based on 5,583 user ratings">8.0</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="7.9 based on 50,853 user ratings">7.9</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="7.9 based on 28,665 user ratings">7.9</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="7.9 based on 18,599 user ratings">7.9</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="7.9 based on 5,118 user ratings">7.9</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="7.9 based on 27,727 user ratings">7.9</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="7.9 based on 6,659 user ratings">7.9</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="7.9 based on 71,850 user ratings">7.9</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="7.9 based on 12,616 user ratings">7.9</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="7.9 based on 14,471 user ratings">7.9</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="7.9 based on 6,745 user ratings">7.9</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="7.9 based on 20,807 user ratings">7.9</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="7.9 based on 10,100 user ratings">7.9</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="7.9 based on 6,512 user ratings">7.9</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="7.9 based on 9,937 user ratings">7.9</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="7.9 based on 6,902 user ratings">7.9</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="7.9 based on 17,721 user ratings">7.9</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="7.9 based on 35,061 user ratings">7.9</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="7.9 based on 110,374 user ratings">7.9</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="7.9 based on 6,878 user ratings">7.9</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="7.9 based on 98,176 user ratings">7.9</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="7.9 based on 47,526 user ratings">7.9</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="7.9 based on 63,185 user ratings">7.9</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="7.9 based on 5,779 user ratings">7.9</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="7.8 based on 5,933 user ratings">7.8</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="7.8 based on 5,191 user ratings">7.8</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="7.8 based on 21,056 user ratings">7.8</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="7.8 based on 13,855 user ratings">7.8</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="7.8 based on 102,379 user ratings">7.8</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="7.8 based on 20,613 user ratings">7.8</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="7.8 based on 5,671 user ratings">7.8</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="7.8 based on 20,677 user ratings">7.8</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="7.8 based on 52,740 user ratings">7.8</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="7.8 based on 6,665 user ratings">7.8</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="7.8 based on 52,683 user ratings">7.8</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="7.8 based on 11,426 user ratings">7.8</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="7.8 based on 33,455 user ratings">7.8</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="7.8 based on 7,701 user ratings">7.8</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="7.8 based on 15,628 user ratings">7.8</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="7.8 based on 8,438 user ratings">7.8</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="7.8 based on 50,270 user ratings">7.8</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="7.8 based on 8,163 user ratings">7.8</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="7.8 based on 23,196 user ratings">7.8</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="7.8 based on 11,498 user ratings">7.8</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="7.8 based on 9,909 user ratings">7.8</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="7.8 based on 20,608 user ratings">7.8</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="7.7 based on 22,142 user ratings">7.7</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="7.7 based on 8,467 user ratings">7.7</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="7.7 based on 25,119 user ratings">7.7</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="7.7 based on 14,300 user ratings">7.7</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="7.7 based on 39,570 user ratings">7.7</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="7.7 based on 14,037 user ratings">7.7</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="7.7 based on 27,049 user ratings">7.7</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="7.7 based on 11,262 user ratings">7.7</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="7.7 based on 12,587 user ratings">7.7</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="7.7 based on 6,221 user ratings">7.7</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="7.7 based on 20,797 user ratings">7.7</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="7.7 based on 6,029 user ratings">7.7</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="7.7 based on 48,835 user ratings">7.7</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="7.7 based on 12,395 user ratings">7.7</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="7.7 based on 7,521 user ratings">7.7</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="7.7 based on 5,976 user ratings">7.7</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="7.7 based on 21,920 user ratings">7.7</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="7.7 based on 5,216 user ratings">7.7</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="7.7 based on 16,252 user ratings">7.7</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="7.7 based on 5,510 user ratings">7.7</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="7.7 based on 7,867 user ratings">7.7</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="7.7 based on 40,016 user ratings">7.7</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="7.7 based on 5,871 user ratings">7.7</strong>

In [9]:
for i in ratings:
    IMDB_Rating.append(i.get_text().replace("\n"," "))
IMDB_Rating

[' 8.5 ',
 ' 8.5 ',
 ' 8.5 ',
 ' 8.5 ',
 ' 8.5 ',
 ' 8.4 ',
 ' 8.4 ',
 ' 8.4 ',
 ' 8.4 ',
 ' 8.4 ',
 ' 8.4 ',
 ' 8.4 ',
 ' 8.4 ',
 ' 8.4 ',
 ' 8.4 ',
 ' 8.3 ',
 ' 8.3 ',
 ' 8.3 ',
 ' 8.3 ',
 ' 8.3 ',
 ' 8.3 ',
 ' 8.3 ',
 ' 8.3 ',
 ' 8.3 ',
 ' 8.3 ',
 ' 8.3 ',
 ' 8.2 ',
 ' 8.2 ',
 ' 8.2 ',
 ' 8.2 ',
 ' 8.2 ',
 ' 8.2 ',
 ' 8.2 ',
 ' 8.2 ',
 ' 8.2 ',
 ' 8.2 ',
 ' 8.2 ',
 ' 8.2 ',
 ' 8.2 ',
 ' 8.2 ',
 ' 8.2 ',
 ' 8.2 ',
 ' 8.2 ',
 ' 8.2 ',
 ' 8.2 ',
 ' 8.2 ',
 ' 8.2 ',
 ' 8.1 ',
 ' 8.1 ',
 ' 8.1 ',
 ' 8.1 ',
 ' 8.1 ',
 ' 8.1 ',
 ' 8.1 ',
 ' 8.1 ',
 ' 8.1 ',
 ' 8.1 ',
 ' 8.1 ',
 ' 8.1 ',
 ' 8.1 ',
 ' 8.1 ',
 ' 8.1 ',
 ' 8.1 ',
 ' 8.1 ',
 ' 8.1 ',
 ' 8.1 ',
 ' 8.1 ',
 ' 8.1 ',
 ' 8.1 ',
 ' 8.1 ',
 ' 8.1 ',
 ' 8.1 ',
 ' 8.1 ',
 ' 8.1 ',
 ' 8.1 ',
 ' 8.1 ',
 ' 8.1 ',
 ' 8.1 ',
 ' 8.1 ',
 ' 8.1 ',
 ' 8.1 ',
 ' 8.1 ',
 ' 8.1 ',
 ' 8.1 ',
 ' 8.1 ',
 ' 8.1 ',
 ' 8.1 ',
 ' 8.1 ',
 ' 8.1 ',
 ' 8.1 ',
 ' 8.1 ',
 ' 8.1 ',
 ' 8.1 ',
 ' 8.0 ',
 ' 8.0 ',
 ' 8.0 ',
 ' 8.0 ',
 ' 8.0 ',
 ' 8.0 ',
 ' 8.0 ',
 ' 8.0 ',
 ' 8.0 ',
 ' 8.0 ',
 ' 8.0 ',
 ' 8.0 ',
 ' 8.0 ',
 ' 8.0 ',
 ' 8.0 ',
 ' 8.0 ',
 ' 8.0 ',
 ' 8.0 ',
 ' 8.0 ',
 ' 8.0 ',
 ' 8.0 ',
 ' 8.0 ',
 ' 8.0 ',
 ' 7.9 ',
 ' 7.9 ',
 ' 7.9 ',
 ' 7.9 ',
 ' 7.9 ',
 ' 7.9 ',
 ' 7.9 ',
 ' 7.9 ',
 ' 7.9 ',
 ' 7.9 ',
 ' 7.9 ',
 ' 7.9 ',
 ' 7.9 ',
 ' 7.9 ',
 ' 7.9 ',
 ' 7.9 ',
 ' 7.9 ',
 ' 7.9 ',
 ' 7.9 ',
 ' 7.9 ',
 ' 7.9 ',
 ' 7.9 ',
 ' 7.9 ',
 ' 7.8 ',
 ' 7.8 ',
 ' 7.8 ',
 ' 7.8 ',
 ' 7.8 ',
 ' 7.8 ',
 ' 7.8 ',
 ' 7.8 ',
 ' 7.8 ',
 ' 7.8 ',
 ' 7.8 ',
 ' 7.8 ',
 ' 7.8 ',
 ' 7.8 ',
 ' 7.8 ',
 ' 7.8 ',
 ' 7.8 ',
 ' 7.8 ',
 ' 7.8 ',
 ' 7.8 ',
 ' 7.8 ',
 ' 7.8 ',
 ' 7.7 ',
 ' 7.7 ',
 ' 7.7 ',
 ' 7.7 ',
 ' 7.7 ',
 ' 7.7 ',
 ' 7.7 ',
 ' 7.7 ',
 ' 7.7 ',
 ' 7.7 ',
 ' 7.7 ',
 ' 7.7 ',
 ' 7.7 ',
 ' 7.7 ',
 ' 7.7 ',
 ' 7.7 ',
 ' 7.7 ',
 ' 7.7 ',
 ' 7.7 ',
 ' 7.7 ',
 ' 7.7 ',
 ' 7.7 ',
 ' 7.7 ',
 ' 7.6 ',
 ' 7.6 ',
 ' 7.6 ',
 ' 7.6 ',
 ' 7.6 ',
 ' 7.6 ',
 ' 7.6 ',
 ' 7.6 ',
 ' 7.6 ',
 ' 7.6 ',
 ' 7.6 ',
 ' 7.6 ',
 ' 7.6 ',
 ' 7.6 ',
 ' 7.6 ',
 ' 7.6 ',
 ' 7.6 ',
 ' 7.6 ',
 ' 7.6 ',
 ' 7.6 ',
 ' 7.6 ',
 ' 7.6 ',
 ' 7.6 ',
 ' 7.6 ',
 ' 7.6 ',
 ' 7.6 ',
 ' 7.6 ',
 ' 7.6 ',
 ' 7.6 ',
 ' 7.5 ',
 ' 7.5 ',
 ' 7.5 ',
 ' 7.5 ',
 ' 7.5 ',
 ' 7.5 ',
 ' 7.5 ',
 ' 7.5 ',
 ' 7.5 ',
 ' 7.5 ',
 ' 7.5 ',
 ' 7.5 ',
 ' 7.5 ',
 ' 7.5 ',
 ' 7.5 ',
 ' 7.5 ',
 ' 7.5 ',
 ' 7.5 ',
 ' 7.5 ',
 ' 7.5 ',
 ' 7.5 ',
 ' 7.5 ',
 ' 7.5 ',
 ' 7.5 ',
 ' 7.5 ',
 ' 7.5 ',
 ' 7.5 ',
 ' 7.5 ',
 ' 7.5 ',
 ' 7.5 ',
 ' 7.5 ',
 ' 7.5 ',
 ' 7.5 ',
 ' 7.5 ',
 ' 7.4 ',
 ' 7.4 ',
 ' 7.4 ']

In [10]:
len(IMDB_Rating)

250

In [11]:
year_of_release=soup.find_all('span',class_="secondaryInfo")
year_of_release

[<span class="secondaryInfo">(1955)</span>,
 <span class="secondaryInfo">(1979)</span>,
 <span class="secondaryInfo">(2018)</span>,
 <span class="secondaryInfo">(1987)</span>,
 <span class="secondaryInfo">(2003)</span>,
 <span class="secondaryInfo">(1959)</span>,
 <span class="secondaryInfo">(1989)</span>,
 <span class="secondaryInfo">(2016)</span>,
 <span class="secondaryInfo">(2018)</span>,
 <span class="secondaryInfo">(2004)</span>,
 <span class="secondaryInfo">(1992)</span>,
 <span class="secondaryInfo">(1993)</span>,
 <span class="secondaryInfo">(2018)</span>,
 <span class="secondaryInfo">(2019)</span>,
 <span class="secondaryInfo">(2009)</span>,
 <span class="secondaryInfo">(2007)</span>,
 <span class="secondaryInfo">(2015)</span>,
 <span class="secondaryInfo">(2016)</span>,
 <span class="secondaryInfo">(1971)</span>,
 <span class="secondaryInfo">(1991)</span>,
 <span class="secondaryInfo">(1956)</span>,
 <span class="secondaryInfo">(2017)</span>,
 <span class="secondaryInfo">(1983)</span>,
 <span class="secondaryInfo">(1957)</span>,
 <span class="secondaryInfo">(2019)</span>,
 <span class="secondaryInfo">(1965)</span>,
 <span class="secondaryInfo">(2002)</span>,
 <span class="secondaryInfo">(1975)</span>,
 <span class="secondaryInfo">(2019)</span>,
 <span class="secondaryInfo">(2019)</span>,
 <span class="secondaryInfo">(2015)</span>,
 <span class="secondaryInfo">(2018)</span>,
 <span class="secondaryInfo">(2020)</span>,
 <span class="secondaryInfo">(2006)</span>,
 <span class="secondaryInfo">(2013)</span>,
 <span class="secondaryInfo">(2016)</span>,
 <span class="secondaryInfo">(2019)</span>,
 <span class="secondaryInfo">(2018)</span>,
 <span class="secondaryInfo">(2018)</span>,
 <span class="secondaryInfo">(2018)</span>,
 <span class="secondaryInfo">(2019)</span>,
 <span class="secondaryInfo">(2018)</span>,
 <span class="secondaryInfo">(2014)</span>,
 <span class="secondaryInfo">(2015)</span>,
 <span class="secondaryInfo">(2016)</span>,
 <span class="secondaryInfo">(1998)</span>,
 <span class="secondaryInfo">(2012)</span>,
 <span class="secondaryInfo">(2014)</span>,
 <span class="secondaryInfo">(2013)</span>,
 <span class="secondaryInfo">(1999)</span>,
 <span class="secondaryInfo">(2005)</span>,
 <span class="secondaryInfo">(2012)</span>,
 <span class="secondaryInfo">(2015)</span>,
 <span class="secondaryInfo">(2014)</span>,
 <span class="secondaryInfo">(2015)</span>,
 <span class="secondaryInfo">(2012)</span>,
 <span class="secondaryInfo">(2013)</span>,
 <span class="secondaryInfo">(2015)</span>,
 <span class="secondaryInfo">(2004)</span>,
 <span class="secondaryInfo">(2000)</span>,
 <span class="secondaryInfo">(1975)</span>,
 <span class="secondaryInfo">(2015)</span>,
 <span class="secondaryInfo">(2003)</span>,
 <span class="secondaryInfo">(2005)</span>,
 <span class="secondaryInfo">(2007)</span>,
 <span class="secondaryInfo">(1992)</span>,
 <span class="secondaryInfo">(1964)</span>,
 <span class="secondaryInfo">(2016)</span>,
 <span class="secondaryInfo">(1960)</span>,
 <span class="secondaryInfo">(2006)</span>,
 <span class="secondaryInfo">(2013)</span>,
 <span class="secondaryInfo">(2012)</span>,
 <span class="secondaryInfo">(2010)</span>,
 <span class="secondaryInfo">(2019)</span>,
 <span class="secondaryInfo">(2011)</span>,
 <span class="secondaryInfo">(2008)</span>,
 <span class="secondaryInfo">(2001)</span>,
 <span class="secondaryInfo">(2003)</span>,
 <span class="secondaryInfo">(1994)</span>,
 <span class="secondaryInfo">(1999)</span>,
 <span class="secondaryInfo">(2015)</span>,
 <span class="secondaryInfo">(2012)</span>,
 <span class="secondaryInfo">(1992)</span>,
 <span class="secondaryInfo">(2001)</span>,
 <span class="secondaryInfo">(2016)</span>,
 <span class="secondaryInfo">(2012)</span>,
 <span class="secondaryInfo">(2000)</span>,
 <span class="secondaryInfo">(2017)</span>,
 <span class="secondaryInfo">(2014)</span>,
 <span class="secondaryInfo">(1995)</span>,
 <span class="secondaryInfo">(2018)</span>,
 <span class="secondaryInfo">(2005)</span>,
 <span class="secondaryInfo">(2016)</span>,
 <span class="secondaryInfo">(2012)</span>,
 <span class="secondaryInfo">(2002)</span>,
 <span class="secondaryInfo">(2006)</span>,
 <span class="secondaryInfo">(2003)</span>,
 <span class="secondaryInfo">(1995)</span>,
 <span class="secondaryInfo">(2013)</span>,
 <span class="secondaryInfo">(2006)</span>,
 <span class="secondaryInfo">(2019)</span>,
 <span class="secondaryInfo">(2006)</span>,
 <span class="secondaryInfo">(1975)</span>,
 <span class="secondaryInfo">(1996)</span>,
 <span class="secondaryInfo">(2019)</span>,
 <span class="secondaryInfo">(2017)</span>,
 <span class="secondaryInfo">(1995)</span>,
 <span class="secondaryInfo">(1968)</span>,
 <span class="secondaryInfo">(2009)</span>,
 <span class="secondaryInfo">(2014)</span>,
 <span class="secondaryInfo">(2019)</span>,
 <span class="secondaryInfo">(2016)</span>,
 <span class="secondaryInfo">(1957)</span>,
 <span class="secondaryInfo">(2005)</span>,
 <span class="secondaryInfo">(2013)</span>,
 <span class="secondaryInfo">(1999)</span>,
 <span class="secondaryInfo">(2013)</span>,
 <span class="secondaryInfo">(2009)</span>,
 <span class="secondaryInfo">(2018)</span>,
 <span class="secondaryInfo">(1958)</span>,
 <span class="secondaryInfo">(2018)</span>,
 <span class="secondaryInfo">(2012)</span>,
 <span class="secondaryInfo">(2015)</span>,
 <span class="secondaryInfo">(1999)</span>,
 <span class="secondaryInfo">(2002)</span>,
 <span class="secondaryInfo">(2014)</span>,
 <span class="secondaryInfo">(2017)</span>,
 <span class="secondaryInfo">(2013)</span>,
 <span class="secondaryInfo">(2017)</span>,
 <span class="secondaryInfo">(2008)</span>,
 <span class="secondaryInfo">(2010)</span>,
 <span class="secondaryInfo">(2015)</span>,
 <span class="secondaryInfo">(2018)</span>,
 <span class="secondaryInfo">(2020)</span>,
 <span class="secondaryInfo">(2012)</span>,
 <span class="secondaryInfo">(2010)</span>,
 <span class="secondaryInfo">(2007)</span>,
 <span class="secondaryInfo">(2003)</span>,
 <span class="secondaryInfo">(2013)</span>,
 <span class="secondaryInfo">(2013)</span>,
 <span class="secondaryInfo">(2009)</span>,
 <span class="secondaryInfo">(2018)</span>,
 <span class="secondaryInfo">(1997)</span>,
 <span class="secondaryInfo">(2015)</span>,
 <span class="secondaryInfo">(2004)</span>,
 <span class="secondaryInfo">(2006)</span>,
 <span class="secondaryInfo">(2019)</span>,
 <span class="secondaryInfo">(2016)</span>,
 <span class="secondaryInfo">(2006)</span>,
 <span class="secondaryInfo">(2015)</span>,
 <span class="secondaryInfo">(2000)</span>,
 <span class="secondaryInfo">(2012)</span>,
 <span class="secondaryInfo">(2015)</span>,
 <span class="secondaryInfo">(2003)</span>,
 <span class="secondaryInfo">(2003)</span>,
 <span class="secondaryInfo">(2013)</span>,
 <span class="secondaryInfo">(2004)</span>,
 <span class="secondaryInfo">(2017)</span>,
 <span class="secondaryInfo">(2007)</span>,
 <span class="secondaryInfo">(2014)</span>,
 <span class="secondaryInfo">(2017)</span>,
 <span class="secondaryInfo">(2019)</span>,
 <span class="secondaryInfo">(2019)</span>,
 <span class="secondaryInfo">(2018)</span>,
 <span class="secondaryInfo">(2001)</span>,
 <span class="secondaryInfo">(2012)</span>,
 <span class="secondaryInfo">(1987)</span>,
 <span class="secondaryInfo">(2016)</span>,
 <span class="secondaryInfo">(1978)</span>,
 <span class="secondaryInfo">(2006)</span>,
 <span class="secondaryInfo">(2011)</span>,
 <span class="secondaryInfo">(2008)</span>,
 <span class="secondaryInfo">(2008)</span>,
 <span class="secondaryInfo">(2004)</span>,
 <span class="secondaryInfo">(2015)</span>,
 <span class="secondaryInfo">(2001)</span>,
 <span class="secondaryInfo">(2015)</span>,
 <span class="secondaryInfo">(2007)</span>,
 <span class="secondaryInfo">(2004)</span>,
 <span class="secondaryInfo">(2008)</span>,
 <span class="secondaryInfo">(2014)</span>,
 <span class="secondaryInfo">(2018)</span>,
 <span class="secondaryInfo">(2016)</span>,
 <span class="secondaryInfo">(2008)</span>,
 <span class="secondaryInfo">(2013)</span>,
 <span class="secondaryInfo">(2016)</span>,
 <span class="secondaryInfo">(2011)</span>,
 <span class="secondaryInfo">(2008)</span>,
 <span class="secondaryInfo">(2012)</span>,
 <span class="secondaryInfo">(1994)</span>,
 <span class="secondaryInfo">(1993)</span>,
 <span class="secondaryInfo">(2017)</span>,
 <span class="secondaryInfo">(2016)</span>,
 <span class="secondaryInfo">(1998)</span>,
 <span class="secondaryInfo">(1990)</span>,
 <span class="secondaryInfo">(2013)</span>,
 <span class="secondaryInfo">(2014)</span>,
 <span class="secondaryInfo">(2011)</span>,
 <span class="secondaryInfo">(2005)</span>,
 <span class="secondaryInfo">(2016)</span>,
 <span class="secondaryInfo">(2007)</span>,
 <span class="secondaryInfo">(2014)</span>,
 <span class="secondaryInfo">(2019)</span>,
 <span class="secondaryInfo">(2007)</span>,
 <span class="secondaryInfo">(2012)</span>,
 <span class="secondaryInfo">(2015)</span>,
 <span class="secondaryInfo">(2009)</span>,
 <span class="secondaryInfo">(1993)</span>,
 <span class="secondaryInfo">(2015)</span>,
 <span class="secondaryInfo">(2019)</span>,
 <span class="secondaryInfo">(2016)</span>,
 <span class="secondaryInfo">(2009)</span>,
 <span class="secondaryInfo">(2015)</span>,
 <span class="secondaryInfo">(2020)</span>,
 <span class="secondaryInfo">(1998)</span>,
 <span class="secondaryInfo">(2018)</span>,
 <span class="secondaryInfo">(2014)</span>,
 <span class="secondaryInfo">(2014)</span>,
 <span class="secondaryInfo">(2011)</span>,
 <span class="secondaryInfo">(2016)</span>,
 <span class="secondaryInfo">(2018)</span>,
 <span class="secondaryInfo">(2002)</span>,
 <span class="secondaryInfo">(2008)</span>,
 <span class="secondaryInfo">(2018)</span>,
 <span class="secondaryInfo">(2020)</span>,
 <span class="secondaryInfo">(2013)</span>,
 <span class="secondaryInfo">(2016)</span>,
 <span class="secondaryInfo">(1998)</span>,
 <span class="secondaryInfo">(2004)</span>,
 <span class="secondaryInfo">(2009)</span>,
 <span class="secondaryInfo">(2018)</span>,
 <span class="secondaryInfo">(2003)</span>,
 <span class="secondaryInfo">(2010)</span>,
 <span class="secondaryInfo">(2016)</span>,
 <span class="secondaryInfo">(2013)</span>,
 <span class="secondaryInfo">(2001)</span>,
 <span class="secondaryInfo">(2019)</span>,
 <span class="secondaryInfo">(2018)</span>,
 <span class="secondaryInfo">(2017)</span>,
 <span class="secondaryInfo">(2017)</span>,
 <span class="secondaryInfo">(2018)</span>,
 <span class="secondaryInfo">(2010)</span>,
 <span class="secondaryInfo">(2005)</span>,
 <span class="secondaryInfo">(2004)</span>,
 <span class="secondaryInfo">(1988)</span>,
 <span class="secondaryInfo">(2015)</span>,
 <span class="secondaryInfo">(2019)</span>,
 <span class="secondaryInfo">(2018)</span>,
 <span class="secondaryInfo">(2007)</span>,
 <span class="secondaryInfo">(2018)</span>]

In [12]:
for i in year_of_release:
    Year_of_Release.append(i.get_text().replace("\n"," "))
Year_of_Release

['(1955)',
 '(1979)',
 '(2018)',
 '(1987)',
 '(2003)',
 '(1959)',
 '(1989)',
 '(2016)',
 '(2018)',
 '(2004)',
 '(1992)',
 '(1993)',
 '(2018)',
 '(2019)',
 '(2009)',
 '(2007)',
 '(2015)',
 '(2016)',
 '(1971)',
 '(1991)',
 '(1956)',
 '(2017)',
 '(1983)',
 '(1957)',
 '(2019)',
 '(1965)',
 '(2002)',
 '(1975)',
 '(2019)',
 '(2019)',
 '(2015)',
 '(2018)',
 '(2020)',
 '(2006)',
 '(2013)',
 '(2016)',
 '(2019)',
 '(2018)',
 '(2018)',
 '(2018)',
 '(2019)',
 '(2018)',
 '(2014)',
 '(2015)',
 '(2016)',
 '(1998)',
 '(2012)',
 '(2014)',
 '(2013)',
 '(1999)',
 '(2005)',
 '(2012)',
 '(2015)',
 '(2014)',
 '(2015)',
 '(2012)',
 '(2013)',
 '(2015)',
 '(2004)',
 '(2000)',
 '(1975)',
 '(2015)',
 '(2003)',
 '(2005)',
 '(2007)',
 '(1992)',
 '(1964)',
 '(2016)',
 '(1960)',
 '(2006)',
 '(2013)',
 '(2012)',
 '(2010)',
 '(2019)',
 '(2011)',
 '(2008)',
 '(2001)',
 '(2003)',
 '(1994)',
 '(1999)',
 '(2015)',
 '(2012)',
 '(1992)',
 '(2001)',
 '(2016)',
 '(2012)',
 '(2000)',
 '(2017)',
 '(2014)',
 '(1995)',
 '(2018)',
 '(2005)',
 '(2016)',
 '(2012)',
 '(2002)',
 '(2006)',
 '(2003)',
 '(1995)',
 '(2013)',
 '(2006)',
 '(2019)',
 '(2006)',
 '(1975)',
 '(1996)',
 '(2019)',
 '(2017)',
 '(1995)',
 '(1968)',
 '(2009)',
 '(2014)',
 '(2019)',
 '(2016)',
 '(1957)',
 '(2005)',
 '(2013)',
 '(1999)',
 '(2013)',
 '(2009)',
 '(2018)',
 '(1958)',
 '(2018)',
 '(2012)',
 '(2015)',
 '(1999)',
 '(2002)',
 '(2014)',
 '(2017)',
 '(2013)',
 '(2017)',
 '(2008)',
 '(2010)',
 '(2015)',
 '(2018)',
 '(2020)',
 '(2012)',
 '(2010)',
 '(2007)',
 '(2003)',
 '(2013)',
 '(2013)',
 '(2009)',
 '(2018)',
 '(1997)',
 '(2015)',
 '(2004)',
 '(2006)',
 '(2019)',
 '(2016)',
 '(2006)',
 '(2015)',
 '(2000)',
 '(2012)',
 '(2015)',
 '(2003)',
 '(2003)',
 '(2013)',
 '(2004)',
 '(2017)',
 '(2007)',
 '(2014)',
 '(2017)',
 '(2019)',
 '(2019)',
 '(2018)',
 '(2001)',
 '(2012)',
 '(1987)',
 '(2016)',
 '(1978)',
 '(2006)',
 '(2011)',
 '(2008)',
 '(2008)',
 '(2004)',
 '(2015)',
 '(2001)',
 '(2015)',
 '(2007)',
 '(2004)',
 '(2008)',
 '(2014)',
 '(2018)',
 '(2016)',
 '(2008)',
 '(2013)',
 '(2016)',
 '(2011)',
 '(2008)',
 '(2012)',
 '(1994)',
 '(1993)',
 '(2017)',
 '(2016)',
 '(1998)',
 '(1990)',
 '(2013)',
 '(2014)',
 '(2011)',
 '(2005)',
 '(2016)',
 '(2007)',
 '(2014)',
 '(2019)',
 '(2007)',
 '(2012)',
 '(2015)',
 '(2009)',
 '(1993)',
 '(2015)',
 '(2019)',
 '(2016)',
 '(2009)',
 '(2015)',
 '(2020)',
 '(1998)',
 '(2018)',
 '(2014)',
 '(2014)',
 '(2011)',
 '(2016)',
 '(2018)',
 '(2002)',
 '(2008)',
 '(2018)',
 '(2020)',
 '(2013)',
 '(2016)',
 '(1998)',
 '(2004)',
 '(2009)',
 '(2018)',
 '(2003)',
 '(2010)',
 '(2016)',
 '(2013)',
 '(2001)',
 '(2019)',
 '(2018)',
 '(2017)',
 '(2017)',
 '(2018)',
 '(2010)',
 '(2005)',
 '(2004)',
 '(1988)',
 '(2015)',
 '(2019)',
 '(2018)',
 '(2007)',
 '(2018)']

In [13]:
len(Year_of_Release)

250

In [14]:
print(len(Movie_Name),len(IMDB_Rating),len(Year_of_Release))

250 250 250

In [15]:
import pandas as pd
movies=pd.DataFrame([])
movies['Movie_Name']=Movie_Name[0:100]
movies['IMDB_Rating']=IMDB_Rating[0:100]
movies['Year_of_Release']=Year_of_Release[0:100]

In [16]:
movies

         Movie_Name IMDB_Rating Year_of_Release
0   Pather Panchali        8.5           (1955)
1          Gol Maal        8.5           (1979)
2          Ratsasan        8.5           (2018)
3           Nayakan        8.5           (1987)
4        Anbe Sivam        8.5           (2003)
..              ...         ...             ...
95       Bommarillu        8.0           (2006)
96          Maqbool        8.0           (2003)
97           Bombay        8.0           (1995)
98            Lucia        8.0           (2013)
99           Omkara        8.0           (2006)

[100 rows x 3 columns]

In [17]:
movies.to_csv("Top_100_Bollywood_Movies_list_IMDB.csv")

# Assignment no. 4- Write a python program to scrap book name, author name, genre and book review of any 5 books from ‘www.bookpage.com’

In [18]:
page2=requests.get("https://bookpage.com/reviews")

In [19]:
soup2=BeautifulSoup(page2.content,'html.parser')

In [20]:
Book_Name=[]
Author_Name=[]
Genre=[]
Book_Review=[]

In [21]:
book_name=soup2.find_all('h4',class_="italic")
for i in book_name:
        full_name=i.find('a').get_text()
        Book_Name.append(full_name)

In [22]:
Book_Name

['Hades, Argentina',
 'Outlawed',
 'Outside, Inside',
 'The Push',
 'I Dream of Popo',
 ' ★ Featherhood',
 'The Sea Gate',
 'A Crooked Tree',
 'Slash and Burn',
 'The Heiress']

In [23]:
author_name=soup2.find_all('p', class_="sans bold")
author_name

[<p class="sans bold">
 Daniel Loedel
 </p>,
 <p class="sans bold">
 Anna North
 </p>,
 <p class="sans bold">
 LeUyen Pham
 </p>,
 <p class="sans bold">
 Ashley Audrain
 </p>,
 <p class="sans bold">
 Livia Blackburne, Julia Kuo
 </p>,
 <p class="sans bold">
 Charlie Gilmour
 </p>,
 <p class="sans bold">
 Jane Johnson
 </p>,
 <p class="sans bold">
 Una Mannion
 </p>,
 <p class="sans bold">
 Claudia Hernández, Julia Sanches
 </p>,
 <p class="sans bold">
 Molly Greeley
 </p>]

In [24]:
for i in author_name:
   
    Author_Name.append(i.get_text().replace("\n",""))
Author_Name

['Daniel Loedel',
 'Anna North',
 'LeUyen Pham',
 'Ashley Audrain',
 'Livia Blackburne, Julia Kuo',
 'Charlie Gilmour',
 'Jane Johnson',
 'Una Mannion',
 'Claudia Hernández, Julia Sanches',
 'Molly Greeley']

In [25]:
genre=soup2.find_all('p', class_="genre-links hidden-phone")
genre

[<p class="genre-links hidden-phone">
 <a href="/search?book_genre=fiction">Fiction</a>
  /
 <a href="/search?book_genre=literary_fiction">Literary Fiction</a>
 </p>,
 <p class="genre-links hidden-phone">
 <a href="/search?book_genre=fiction">Fiction</a>
  /
 <a href="/search?book_genre=dystopian_fiction">Dystopian Fiction</a>
  /
 <a href="/search?book_genre=western">Western</a>
 </p>,
 <p class="genre-links hidden-phone">
 <a href="/search?book_genre=children_s">Children's</a>
  /
 <a href="/search?book_genre=children_s_picture_book">Children's Picture Book</a>
 </p>,
 <p class="genre-links hidden-phone">
 <a href="/search?book_genre=fiction">Fiction</a>
  /
 <a href="/search?book_genre=family_drama">Family Drama</a>
 </p>,
 <p class="genre-links hidden-phone">
 <a href="/search?book_genre=children_s">Children's</a>
  /
 <a href="/search?book_genre=children_s_picture_book">Children's Picture Book</a>
 </p>,
 <p class="genre-links hidden-phone">
 <a href="/search?book_genre=nonfiction">Nonfiction</a>
  /
 <a href="/search?book_genre=biography_memoir">Biography &amp; Memoir</a>
  /
 <a href="/search?book_genre=memoir">Memoir</a>
 </p>,
 <p class="genre-links hidden-phone">
 <a href="/search?book_genre=fiction">Fiction</a>
  /
 <a href="/search?book_genre=family_saga">Family Saga</a>
 </p>,
 <p class="genre-links hidden-phone">
 <a href="/search?book_genre=fiction">Fiction</a>
  /
 <a href="/search?book_genre=coming_of_age">Coming of Age</a>
 </p>,
 <p class="genre-links hidden-phone">
 <a href="/search?book_genre=fiction">Fiction</a>
  /
 <a href="/search?book_genre=historical_fiction">Historical Fiction</a>
 </p>,
 <p class="genre-links hidden-phone">
 <a href="/search?book_genre=fiction">Fiction</a>
  /
 <a href="/search?book_genre=literary_fiction">Literary Fiction</a>
 </p>]

In [26]:
for i in genre:
   
    Genre.append(i.get_text().replace("\n",""))
Genre

['Fiction / Literary Fiction',
 'Fiction / Dystopian Fiction / Western',
 "Children's / Children's Picture Book",
 'Fiction / Family Drama',
 "Children's / Children's Picture Book",
 'Nonfiction / Biography & Memoir / Memoir',
 'Fiction / Family Saga',
 'Fiction / Coming of Age',
 'Fiction / Historical Fiction',
 'Fiction / Literary Fiction']

In [27]:
book_review=soup2.find_all('p', class_="excerpt")
book_review

[<p class="excerpt">
 As Tomás reenters the world of Argentina’s dirty war, time blurs, and the surreal blends with reality. As he relives trauma and torture, readers experience it with him, seeing a slice of history that is rarely talked about and feeling immersed in the ways that love, guilt and regret drive so many...
 </p>,
 <p class="excerpt">
 <p>This ain’t no Louis L’Amour tale of the Wild West. <strong>Outlawed</strong>, the third novel by Anna North, is a gender-bending, genre-hopping yarn that’s part frontier novel, part <em>Handmaid’s Tale </em>and all ripsnorting fun.</p>
 </p>,
 <p class="excerpt">
 <p>LeUyen Pham’s <strong>Outside, Inside </strong>addresses the subject of the COVID-19 pandemic for young readers with sensitivity and compassion.</p>
 </p>,
 <p class="excerpt">
 <p>It’s easy to think of intimate, single-POV novels as somewhat simple narrative exercises, but Ashley Audrain’s gripping debut is proof that this is an illusion. In the hands of the right storyteller, even the most compact novels can be works of great complexity.</p>
 </p>,
 <p class="excerpt">
 <p>A young girl stays in touch with her beloved grandmother, Popo, when her family moves to the United States from Taiwan in this exuberant picture book.</p>
 </p>,
 <p class="excerpt">
 In folklore, magpies are said to bring bad luck, but that certainly wasn’t the case for Charlie Gilmour. An abandoned baby bird helped this young British author finally exorcise the long shadow cast by his biological father, whoabandoned him as an infant.
 </p>,
 <p class="excerpt">
 Jane Johnson’s latest novel, <strong>The Sea Gate</strong>, is beautiful story of love, loss and pain, bouncing between wartime memories of the 1940s and present day.
 </p>,
 <p class="excerpt">
 <p>As 15-year-old Libby Gallagher ponders several dark moments in rock ’n’ roll history, she muses, “It all said to me that chaotic and dark forces were spinning around us. One foot wrong, and you’d be pulled into the vortex.” Unfortunately, a multitude of missteps have...</p>
 </p>,
 <p class="excerpt">
 <p><strong>Slash and Burn</strong> is an ember of a novel. Originally published in Spanish, this restrained narrative about a mother’s sacrifice surges with hot undercurrents of danger and memory.</p>
 </p>,
 <p class="excerpt">
 <p>Enter Molly Greeley’s novel <strong>The Heiress</strong>, an entertaining elaboration to satisfy generations of readers who have wondered and theorized about Anne de Bourgh. In perfectly Austenesque style, Greeley reveals the backstory of the Rosings Park heiress and just what made her so sickly, so...</p>
 </p>]

In [28]:
for i in book_review:
   
    Book_Review.append(i.get_text().replace("\n",""))
Book_Review

['As Tomás reenters the world of Argentina’s dirty war, time blurs, and the surreal blends with reality. As he relives trauma and torture, readers experience it with him, seeing a slice of history that is rarely talked about and feeling immersed in the ways that love, guilt and regret drive so many...',
 'This ain’t no Louis L’Amour tale of the Wild West. Outlawed, the third novel by Anna North, is a gender-bending, genre-hopping yarn that’s part frontier novel, part Handmaid’s Tale and all ripsnorting fun.',
 'LeUyen Pham’s Outside, Inside addresses the subject of the COVID-19 pandemic for young readers with sensitivity and compassion.',
 'It’s easy to think of intimate, single-POV novels as somewhat simple narrative exercises, but Ashley Audrain’s gripping debut is proof that this is an illusion. In the hands of the right storyteller, even the most compact novels can be works of great complexity.',
 'A young girl stays in touch with her beloved grandmother, Popo, when her family moves to the United States from Taiwan in this exuberant picture book.',
 'In folklore, magpies are said to bring bad luck, but that certainly wasn’t the case for Charlie Gilmour. An abandoned baby bird helped this young British author finally exorcise the long shadow cast by his biological father, whoabandoned him as an infant.',
 'Jane Johnson’s latest novel, The Sea Gate, is beautiful story of love, loss and pain, bouncing between wartime memories of the 1940s and present day.',
 'As 15-year-old Libby Gallagher ponders several dark moments in rock ’n’ roll history, she muses, “It all said to me that chaotic and dark forces were spinning around us. One foot wrong, and you’d be pulled into the vortex.” Unfortunately, a multitude of missteps have...',
 'Slash and Burn is an ember of a novel. Originally published in Spanish, this restrained narrative about a mother’s sacrifice surges with hot undercurrents of danger and memory.',
 'Enter Molly Greeley’s novel The Heiress, an entertaining elaboration to satisfy generations of readers who have wondered and theorized about Anne de Bourgh. In perfectly Austenesque style, Greeley reveals the backstory of the Rosings Park heiress and just what made her so sickly, so...']

In [29]:
len(Book_Review)

10

In [30]:
import pandas as pd
book=pd.DataFrame([])
book['Book_Name']=Book_Name
book['Author_Name']=Author_Name
book['Genre']=Genre
book['Book_Review']=Book_Review

In [31]:
book

,Book_Name,Author_Name,Genre,Book_Review
0,"Hades, Argentina",Daniel Loedel,Fiction / Literary Fiction,As Tomás reenters the world of Argentina’s dir...
1,Outlawed,Anna North,Fiction / Dystopian Fiction / Western,This ain’t no Louis L’Amour tale of the Wild W...
2,"Outside, Inside",LeUyen Pham,Children's / Children's Picture Book,"LeUyen Pham’s Outside, Inside addresses the su..."
3,The Push,Ashley Audrain,Fiction / Family Drama,"It’s easy to think of intimate, single-POV nov..."
4,I Dream of Popo,"Livia Blackburne, Julia Kuo",Children's / Children's Picture Book,A young girl stays in touch with her beloved g...
5,★ Featherhood,Charlie Gilmour,Nonfiction / Biography & Memoir / Memoir,"In folklore, magpies are said to bring bad luc..."
6,The Sea Gate,Jane Johnson,Fiction / Family Saga,"Jane Johnson’s latest novel, The Sea Gate, is ..."
7,A Crooked Tree,Una Mannion,Fiction / Coming of Age,As 15-year-old Libby Gallagher ponders several...
8,Slash and Burn,"Claudia Hernández, Julia Sanches",Fiction / Historical Fiction,Slash and Burn is an ember of a novel. Origina...
9,The Heiress,Molly Greeley,Fiction / Literary Fiction,"Enter Molly Greeley’s novel The Heiress, an en..."